/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Hypulse primary: gold/amber
        'primary':                '#ffb952',
        'on-primary':             '#452b00',
        'primary-fixed':          '#ffddb4',
        'primary-fixed-dim':      '#ffb952',
        'primary-container':      '#986300',
        'on-primary-container':   '#fff0e1',
        'on-primary-fixed':       '#291800',
        'on-primary-fixed-variant': '#633f00',
        'inverse-primary':        '#825500',
        // Hypulse secondary: lavender
        'secondary':              '#c1c1ff',
        'on-secondary':           '#1300a9',
        'secondary-fixed':        '#e1dfff',
        'secondary-fixed-dim':    '#c1c1ff',
        'secondary-container':    '#2a21da',
        'on-secondary-fixed':     '#08006c',
        'on-secondary-fixed-variant': '#271cd8',
        'on-secondary-container': '#b0b1ff',
        // Hypulse tertiary: neon green (profit)
        'tertiary':               '#33e43d',
        'on-tertiary':            '#003a04',
        'tertiary-fixed':         '#74ff6b',
        'tertiary-fixed-dim':     '#33e43d',
        'tertiary-container':     '#008115',
        'on-tertiary-fixed':      '#002202',
        'on-tertiary-fixed-variant': '#005309',
        'on-tertiary-container':  '#d2ffc6',
        // Surfaces
        'surface':                '#131313',
        'surface-dim':            '#131313',
        'surface-bright':         '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low':  '#1c1b1b',
        'surface-container':      '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant':        '#353534',
        'surface-tint':           '#ffb952',
        // On-surface text
        'on-surface':             '#e5e2e1',
        'on-surface-variant':     '#c6c4d9',
        'inverse-surface':        '#e5e2e1',
        'inverse-on-surface':     '#313030',
        // Misc
        'background':             '#131313',
        'on-background':          '#e5e2e1',
        'outline':                '#908fa2',
        'outline-variant':        '#464556',
        'error':                  '#ffb4ab',
        'on-error':               '#690005',
        'error-container':        '#93000a',
        'on-error-container':     '#ffdad6',
      },
      fontFamily: {
        headline: ['"Space Grotesk"', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
        mono:     ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm:      '0.125rem',
        md:      '0.25rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        '2xl':   '0.5rem',
        full:    '0.75rem',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
