// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyBazaar.Data;

#nullable disable

namespace SkyBazaar.Migrations
{
    [DbContext(typeof(SkyBazaarDbContext))]
    [Migration("20260328180416_20260328181000_SyncModelAfterPrecisionChange")]
    partial class _20260328181000_SyncModelAfterPrecisionChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("SkyBazaar.Models.BazaarItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("SkyBazaar.Models.PriceSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BazaarItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BuyMovingWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyOrdersCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("decimal(20,4)");

                    b.Property<long>("BuyVolume")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExternalImport")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SellMovingWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SellOrdersCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(20,4)");

                    b.Property<long>("SellVolume")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SerializedBuyOrders")
                        .HasColumnType("blob");

                    b.Property<byte[]>("SerializedSellOrders")
                        .HasColumnType("blob");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BazaarItemId", "Timestamp")
                        .IsUnique();

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("SkyBazaar.Models.PriceSnapshot", b =>
                {
                    b.HasOne("SkyBazaar.Models.BazaarItem", "BazaarItem")
                        .WithMany("Snapshots")
                        .HasForeignKey("BazaarItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BazaarItem");
                });

            modelBuilder.Entity("SkyBazaar.Models.BazaarItem", b =>
                {
                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
